name: github-workflow

on: "push"

env: 
  ARTIFICATE_NAME: test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
  
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFICATE_NAME }}
        path: .

  
    
